import 'flight_recorder.dart';

/// Synthesizes standalone, executable Flutter widget test files (`repro_test.dart`)
/// from recorded FlightRecorder sessions.
class ReproTestGenerator {
  /// Generates a complete, copy-pasteable Dart test file string from the flight log.
  static String generate({
    String? testName,
    String? initialWidgetName,
  }) {
    final events = FlightRecorder.getSnapshotEvents();
    final name = testName ?? 'Reproduction Test';
    final widgetName = initialWidgetName ?? 'MyApp()';

    final buffer = StringBuffer();
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln('// Auto-generated by FlutterPilot Flight Recorder');
    buffer.writeln('// Run with: flutter test test/repro_test.dart');
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:flutter_test/flutter_test.dart';");
    buffer.writeln();
    buffer.writeln('void main() {');
    buffer.writeln("  testWidgets('$name', (WidgetTester tester) async {");
    buffer.writeln('    // 1. Mount initial application or screen');
    buffer.writeln('    await tester.pumpWidget(const $widgetName);');
    buffer.writeln('    await tester.pumpAndSettle();');
    buffer.writeln();

    if (events.isEmpty) {
      buffer.writeln('    // No flight recorder actions were captured.');
      buffer.writeln('    expect(find.byType($widgetName), findsOneWidget);');
    } else {
      buffer.writeln('    // 2. Replay recorded user gestures & flight timeline');
      for (final event in events) {
        if (event.category == 'gesture') {
          final action = event.action;
          final data = event.data;

          if (action == 'tapWidget') {
            final key = data['key']?.toString();
            if (key != null) {
              if (key.startsWith("ElevatedButton['") ||
                  key.startsWith("Button['") ||
                  key.startsWith("Text['")) {
                final text = key.split("'")[1];
                buffer.writeln("    await tester.tap(find.text('$text'));");
              } else {
                buffer.writeln("    await tester.tap(find.byKey(const ValueKey('$key')));");
              }
              buffer.writeln('    await tester.pumpAndSettle();');
            }
          } else if (action == 'enterText') {
            final key = data['key']?.toString();
            final text = data['text']?.toString() ?? '';
            if (key != null) {
              buffer.writeln("    await tester.enterText(find.byKey(const ValueKey('$key')), '$text');");
              buffer.writeln('    await tester.pumpAndSettle();');
            }
          } else if (action == 'tapAt') {
            final x = data['x'];
            final y = data['y'];
            if (x != null && y != null) {
              buffer.writeln('    await tester.tapAt(const Offset($x, $y));');
              buffer.writeln('    await tester.pumpAndSettle();');
            }
          }
        } else if (event.category == 'route') {
          final name = event.data['name']?.toString();
          if (name != null && name.isNotEmpty) {
            buffer.writeln("    // Navigated to route: $name");
          }
        } else if (event.category == 'state') {
          buffer.writeln("    // State shift: ${event.action} -> ${event.data['value']}");
        }
      }

      buffer.writeln();
      buffer.writeln('    // 3. Verification — verify app completes flow without throwing');
      buffer.writeln('    expect(tester.takeException(), isNull);');
    }

    buffer.writeln('  });');
    buffer.writeln('}');
    return buffer.toString();
  }
}
