import 'flight_recorder.dart';

/// Supported testing frameworks for synthesized test suites.
enum TestFramework {
  patrol,
  integrationTest,
  widgetTest;

  static TestFramework fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'patrol':
        return TestFramework.patrol;
      case 'integration':
      case 'integration_test':
      case 'integrationtest':
        return TestFramework.integrationTest;
      case 'widget':
      case 'widget_test':
      case 'widgettest':
      default:
        return TestFramework.widgetTest;
    }
  }
}

/// Generates production-ready, clean test code for Patrol, Integration Test,
/// and Flutter Widget Test from recorded FlightRecorder sessions.
class TestSynthesizer {
  /// Generates code for the requested [framework].
  static String generate({
    required TestFramework framework,
    List<FlightEvent>? events,
    String? testName,
    String? appWidget,
  }) {
    final flightEvents = events ?? FlightRecorder.getSnapshotEvents();
    switch (framework) {
      case TestFramework.patrol:
        return generatePatrolTest(
          flightEvents,
          testName: testName,
          appWidget: appWidget,
        );
      case TestFramework.integrationTest:
        return generateIntegrationTest(
          flightEvents,
          testName: testName,
        );
      case TestFramework.widgetTest:
        return generateWidgetTest(
          flightEvents,
          testName: testName,
          appWidget: appWidget,
        );
    }
  }

  /// Synthesizes a modern Patrol integration test.
  static String generatePatrolTest(
    List<FlightEvent> events, {
    String? testName,
    String? appWidget,
  }) {
    final name = testName ?? 'User Journey Flow';
    final widgetName = appWidget ?? 'MyApp()';

    final buffer = StringBuffer();
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln('// Auto-generated by FlutterPilot Test Synthesizer (Patrol)');
    buffer.writeln('// Run with: patrol test integration_test/patrol_flow_test.dart');
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:patrol/patrol.dart';");
    buffer.writeln();
    buffer.writeln('void main() {');
    buffer.writeln("  patrolTest('$name', (\$) async {");
    buffer.writeln('    // 1. Mount application');
    buffer.writeln('    await \$.pumpWidgetAndSettle(const $widgetName);');
    buffer.writeln();

    if (events.isEmpty) {
      buffer.writeln('    // Verify root widget is visible');
      buffer.writeln('    expect(\$($widgetName), findsOneWidget);');
    } else {
      buffer.writeln('    // 2. Replay recorded actions');
      for (final event in events) {
        if (event.category == 'gesture') {
          final action = event.action;
          final data = event.data;

          if (action == 'tapWidget') {
            final key = data['key']?.toString();
            if (key != null) {
              final selector = _formatPatrolSelector(key);
              buffer.writeln('    await $selector.tap();');
            }
          } else if (action == 'enterText') {
            final key = data['key']?.toString();
            final text = data['text']?.toString() ?? '';
            if (key != null) {
              final selector = _formatPatrolSelector(key);
              buffer.writeln("    await $selector.enterText('$text');");
            }
          } else if (action == 'tapAt') {
            final x = data['x'];
            final y = data['y'];
            if (x != null && y != null) {
              buffer.writeln('    await \$.tester.tapAt(const Offset($x, $y));');
              buffer.writeln('    await \$.pumpAndSettle();');
            }
          }
        } else if (event.category == 'route') {
          final name = event.data['name']?.toString();
          if (name != null && name.isNotEmpty) {
            buffer.writeln("    // Route changed to: $name");
          }
        } else if (event.category == 'state') {
          buffer.writeln("    // State mutation: ${event.action} -> ${event.data['value']}");
        }
      }

      buffer.writeln();
      buffer.writeln('    // 3. Final verification assertion');
      buffer.writeln('    expect(\$.tester.takeException(), isNull);');
    }

    buffer.writeln('  });');
    buffer.writeln('}');
    return buffer.toString();
  }

  /// Synthesizes a standard Flutter Integration Test (`integration_test`).
  static String generateIntegrationTest(
    List<FlightEvent> events, {
    String? testName,
    String? appEntrypoint,
  }) {
    final name = testName ?? 'User Journey Integration Test';

    final buffer = StringBuffer();
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln('// Auto-generated by FlutterPilot Test Synthesizer (Integration Test)');
    buffer.writeln('// Run with: flutter test integration_test/app_test.dart');
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:flutter_test/flutter_test.dart';");
    buffer.writeln("import 'package:integration_test/integration_test.dart';");
    buffer.writeln();
    buffer.writeln('void main() {');
    buffer.writeln('  IntegrationTestWidgetsFlutterBinding.ensureInitialized();');
    buffer.writeln();
    buffer.writeln("  testWidgets('$name', (WidgetTester tester) async {");
    buffer.writeln('    // 1. Launch application entrypoint');
    buffer.writeln('    // import and call app.main();');
    buffer.writeln('    await tester.pumpAndSettle();');
    buffer.writeln();

    _writeFlutterTestBody(buffer, events);

    buffer.writeln('  });');
    buffer.writeln('}');
    return buffer.toString();
  }

  /// Synthesizes a standard Flutter Widget Test (`testWidgets`).
  static String generateWidgetTest(
    List<FlightEvent> events, {
    String? testName,
    String? appWidget,
  }) {
    final name = testName ?? 'User Journey Widget Test';
    final widgetName = appWidget ?? 'MyApp()';

    final buffer = StringBuffer();
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln('// Auto-generated by FlutterPilot Test Synthesizer (Widget Test)');
    buffer.writeln('// Run with: flutter test test/journey_test.dart');
    buffer.writeln('// ---------------------------------------------------------------------------');
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln("import 'package:flutter_test/flutter_test.dart';");
    buffer.writeln();
    buffer.writeln('void main() {');
    buffer.writeln("  testWidgets('$name', (WidgetTester tester) async {");
    buffer.writeln('    // 1. Mount target screen or app');
    buffer.writeln('    await tester.pumpWidget(const $widgetName);');
    buffer.writeln('    await tester.pumpAndSettle();');
    buffer.writeln();

    _writeFlutterTestBody(buffer, events);

    buffer.writeln('  });');
    buffer.writeln('}');
    return buffer.toString();
  }

  static void _writeFlutterTestBody(StringBuffer buffer, List<FlightEvent> events) {
    if (events.isEmpty) {
      buffer.writeln('    // No recorded actions.');
      buffer.writeln('    expect(tester.takeException(), isNull);');
      return;
    }

    buffer.writeln('    // 2. Replay recorded actions');
    for (final event in events) {
      if (event.category == 'gesture') {
        final action = event.action;
        final data = event.data;

        if (action == 'tapWidget') {
          final key = data['key']?.toString();
          if (key != null) {
            final finder = _formatFlutterFinder(key);
            buffer.writeln('    await tester.tap($finder);');
            buffer.writeln('    await tester.pumpAndSettle();');
          }
        } else if (action == 'enterText') {
          final key = data['key']?.toString();
          final text = data['text']?.toString() ?? '';
          if (key != null) {
            final finder = _formatFlutterFinder(key);
            buffer.writeln("    await tester.enterText($finder, '$text');");
            buffer.writeln('    await tester.pumpAndSettle();');
          }
        } else if (action == 'tapAt') {
          final x = data['x'];
          final y = data['y'];
          if (x != null && y != null) {
            buffer.writeln('    await tester.tapAt(const Offset($x, $y));');
            buffer.writeln('    await tester.pumpAndSettle();');
          }
        }
      } else if (event.category == 'route') {
        final name = event.data['name']?.toString();
        if (name != null && name.isNotEmpty) {
          buffer.writeln("    // Route transitioned to: $name");
        }
      } else if (event.category == 'state') {
        buffer.writeln("    // State mutation: ${event.action} -> ${event.data['value']}");
      }
    }

    buffer.writeln();
    buffer.writeln('    // 3. Verification assertion');
    buffer.writeln('    expect(tester.takeException(), isNull);');
  }

  static String _formatPatrolSelector(String key) {
    if (key.startsWith("ElevatedButton['") ||
        key.startsWith("Button['") ||
        key.startsWith("Text['") ||
        key.startsWith("Tooltip['") ||
        key.startsWith("TextField['")) {
      final parts = key.split("'");
      if (parts.length >= 2) {
        final text = parts[1];
        return "\$('$text')";
      }
    }
    return "\$(const ValueKey('$key'))";
  }

  static String _formatFlutterFinder(String key) {
    if (key.startsWith("ElevatedButton['") ||
        key.startsWith("Button['") ||
        key.startsWith("Text['") ||
        key.startsWith("Tooltip['") ||
        key.startsWith("TextField['")) {
      final parts = key.split("'");
      if (parts.length >= 2) {
        final text = parts[1];
        return "find.text('$text')";
      }
    }
    return "find.byKey(const ValueKey('$key'))";
  }
}
